export const marineverseLinks = [
  { name: 'website', title: 'MarineVerse', description: 'Sailing apps and community', url: 'https://www.marineverse.com/' },
  { name: 'llms', title: 'Agent guide', description: 'MarineVerse information for agents', url: 'https://www.marineverse.com/llms.txt' },
  { name: 'dashboard', title: 'Dashboard', description: 'Your sailing account and activities', url: 'https://www.marineverse.com/dashboard-app' },
  { name: 'my-profile', title: 'My profile', description: 'Account management', url: 'https://www.marineverse.com/my-profile' },
  { name: 'try-sailing', title: 'Try sailing', description: 'Try sailing in your browser', url: 'https://www.marineverse.com/try-sailing' },
  { name: 'history', title: 'Sailing Club history', description: 'MarineVerse Sailing Club updates and development timeline', url: 'https://www.marineverse.com/marineverse-sailing-club/history' },
  { name: 'links', title: 'Useful links', description: 'MarineVerse destinations and resources', url: 'https://www.marineverse.com/links' },
  { name: 'steam', title: 'Steam', description: 'MarineVerse on Steam', url: 'https://www.marineverse.com/steam' },
  { name: 'quest', title: 'Quest', description: 'MarineVerse on Meta Quest', url: 'https://www.marineverse.com/quest' },
  { name: 'cli', title: 'CLI', description: 'Install the MarineVerse CLI', url: 'https://www.marineverse.com/cli' },
  { name: 'mcp', title: 'MCP', description: 'Connect an assistant to MarineVerse', url: 'https://www.marineverse.com/mcp' },
  { name: 'discord', title: 'Discord', description: 'Join MarineVerse Discord chat', url: 'https://discord.gg/marineverse' },
  { name: 'support', title: 'Support', description: 'Contact MarineVerse', url: 'https://www.marineverse.com/contact' },
  { name: 'blog', title: 'Blog', description: 'MarineVerse news and stories', url: 'https://blog.marineverse.com/' },
  { name: 'learn-to-sail', title: 'Learn to sail', description: 'Learn how to sail with MarineVerse', url: 'https://www.marineverse.com/learn-how-to-sail' },
  { name: 'racing-dashboard', title: 'Racing dashboard', description: 'MarineVerse Sailing Club racing dashboard', url: 'https://www.marineverse.com/marineverse-cup/racing-dashboard' },
  { name: 'multiplayer', title: 'Multiplayer', description: 'MarineVerse Sailing Club multiplayer sailing', url: 'https://www.marineverse.com/marineverse-cup/multiplayer' },
] as const;
